config/routes.rb
Rails.application.routes.draw do


  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'settings/index'
  get    'new_connection',      to: 'settings#new'
  get    'collaborations',      to: 'collaborations#index'
  get    'collaborations/:id' , to: 'collaborations#show', as: 'collaboration'
      
  resources :users do
    member do
    end
  end

#  resources :account_activations, only: [:edit]
   resources :password_resets,     only: [:new, :create, :edit, :update]
   resources :projects,            only: [:new, :create, :edit, :update , :index , :show]

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  attr_accessor :available ,  :selected
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :collaborations
  has_many :projects , :through => :collaborations

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Returns a user's status feed.
  def feed
  end


       def available
           @available
       end
       def available=(val)
            @available = val
       end

       def selected
           @selected
       end
       def selected=(val)
            @selected = val
       end


  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(self.activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :admin_user,     only: [:destroy  ] 
  before_action :correct_user,   only: [:edit, :update]

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.activate
         # @user.send_activation_email
         # flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def resolve_changes( format )

        if params[:move] == '>>'
             params[:user][:available].each do | add_project |
                    @user.collaborations.create( project_id: add_project ) unless add_project.empty?
                    format.html { redirect_to notice: 'User Added' , action: "edit" , id: @user.id  }
             end
             format.html { redirect_to  action: "edit" , id: @user.id  }
        end

        if params[:move] == '<<'
             params[:user][:selected].each do | rm_project |
                    c = @user.collaborations.where( project_id: rm_project).first unless rm_project.empty?
                    c.destroy unless c.nil?
                    format.html { redirect_to notice: 'User Removed' , action: "edit" , id: @user.id  }
             end
             format.html { redirect_to  action: "edit" , id: @user.id  }
        end
  end

  def update

    respond_to do |format|
      if @user.update( user_params )
        resolve_changes( format )
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation , :available , :selected )
    end

    # Before filters

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      if not ( current_user?(@user) || current_user.admin? ) 
          redirect_to(root_url)  
      end
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def role_img( user )
    if user.admin == true
      return "admin.svg"
    else
      return "user.svg"
    end
  end
  
  def role( user )
    if user.admin == true
      return "Adminstrator"
    else
      return "User"
    end
  end

  def edit_mode
      logger.debug self.action_name

      if self.action_name == "show"
           return false
      end

      return true
  end

  
end

app/views/users/_collaborations.html.erb
<style type="text/css">  
     select { 
         width:300px; 
            } 
     .span  {
         display: table-cell;
         vertical-align: middle;
            }
.knob {
  display: table;
  height: 100%;
  width: 100%;
  text-align: center;
}
</style>

<div class="row" >
	<div class="col-xs-5 col-sm-5" style="height:35px" >
        <h2> Available </h2>
	</div>
	<div class="col-xs-2 col-sm-2" style="height:35px">
	</div>
	<div class="col-xs-5 col-sm-5" style="height:35px">
        <h2> Selected </h2>
	</div>
</div>
<div class="row">
	<div class="col-xs-5 col-sm-5" >
		<%= form_for( @user ) do |a| %>
		     <%= a.select(:available  , 
		                   options_from_collection_for_select(Project.all - @user.projects , :id, :name , {} ),
		                   { :prompt => nil },
		                   { :multiple => true, :size => 20 , :id => "available" }) %>
	</div>
	
	<div class="col-xs-2 col-sm-2" style="height:350px" >
             <div class="knob" >
                <% if edit_mode %>
                      <span class="span"> 
                                 <%= a.submit "<<", name: 'move' , value: '<<',   class: "btn btn-primary" %>
                      </span>
                      <span class="span"> 
                                 <%= a.submit ">>", name: 'move' , value: '>>',  class: "btn btn-primary" %>
                      </span>
		<% end %>
             </div>
        </div>

	<div class="col-xs-5 col-sm-5"  >
		     <%= a.select(:selected  , 
		                   options_from_collection_for_select(@user.projects, :id, :name  , {} ),
		                   { :prompt =>  nil },
		                   { :multiple => true, :size => 20 , :id => "selected"  } ) %>
		<% end %>
	</div>
</div>

app/views/users/_details.html.erb
<li>
  <div class='name'>      <%= @user.name %> </div>
  <div class='email'>     <%= @user.email %> </div>
  <% if current_user.admin?  %>
     
     I would Delete here
  <% end %>
</li>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_manage.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>


<div class="center container">
  <div class="row">
    <div class="center col-xs-12 col-sm-12" >
        <h3> <%= role(@user) %>  </h3>
    </div>
  </div>
  <%= render 'users/collaborations' %>
</div>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', projects_path %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<% if  current_user == @user %>
     <h1>Update your profile</h1>
<% else %>
     <h1>Update <%=@user.name%>'s profile</h1>
<% end %>


 <%= render 'users/manage' %>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>Users</h1>
<%= will_paginate %>

    <div class="container">
        <div class="row">
			<div class="h4 col-xs-2 col-sm-2">User Name</div>
			<div class="h4 col-xs-2 col-md-2">Email</div>
			<div class="h4 col-xs-1 col-sm-1">Role</div>
			<div class="h4 col-xs-1 col-sm-1">Actions</div>
		</div>
    </div>

	<ul></ul>

	<div class="container">
    <% @users.each do |user| %>
        <div class="row">
			<div class="col-xs-2 col-sm-2"><%= user.name  %></div>
			<div class="col-xs-2 col-md-2"><%= user.email %></div>
		    <div class="col-xs-1 col-sm-1"><%= image_tag( role_img( user )  , title:  role( user )  , size: 18 ) %>  </div>
			<div class="col-xs-1 col-sm-1"><%= link_to image_tag("view.svg" , title: "User Details" , size: 18 ), user_path(user) %>
                                           <% if current_user.admin? || user == current_user  %>
  		                                              <%= link_to image_tag("edit.svg" , title: "Edit User"    , size: 18 ), edit_user_path(user) %>
                                           <% end %> </div>
		</div>
    <% end %>
    </div>
  
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

 <%= render 'users/manage' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1> User Profile </h1>

 <%= render 'users/manage' %>

   