config/routes.rb
Rails.application.routes.draw do


  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'settings/index'
  get    'new_connection',      to: 'settings#new'
  get    'collaborations',      to: 'collaborations#index'
  get    'collaborations/:id' , to: 'collaborations#show', as: 'collaboration'
      
  resources :users do
    member do
    end
  end

#  resources :account_activations, only: [:edit]
   resources :password_resets,     only: [:new, :create, :edit, :update]
   resources :projects,            only: [:new, :create, :edit, :update , :index , :show]

end

app/models/project.rb
class Project < ApplicationRecord
     has_many :collaborations
     has_many :users , :through => :collaborations

   attr_accessor :available ,  :selected

       def available
           @available
       end
       def available=(val)
            @available = val
       end
   
       def selected
           @selected
       end
       def selected=(val)
            @selected = val
       end
   
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :admin_user,  only: [:destroy , :edit, :update, :new ]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.paginate(page: params[:page])
  end

  # GET /projects/1
  # GET /projects/1.json

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def resolve_changes( format )
       
        if params[:move] == '>>' 
	     params[:project][:available].each do | add_user |
                    @project.collaborations.create( user_id: add_user ) unless add_user.empty?
                    format.html { redirect_to notice: 'User Added' , action: "edit" , id: @project.id  }
             end
             format.html { redirect_to  action: "edit" , id: @project.id  }
        end 

        if params[:move] == '<<' 
	     params[:project][:selected].each do | rm_user |
                    c = @project.collaborations.where( user_id: rm_user).first unless rm_user.empty?
                    c.destroy unless c.nil?
                    format.html { redirect_to notice: 'User Removed' , action: "edit" , id: @project.id  }
             end
             format.html { redirect_to  action: "edit" , id: @project.id  }
        end 
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update

    respond_to do |format|
      if @project.update(project_params)
        resolve_changes( format )
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :active , :available , :selected)
    end

    # Confirms an admin user.
    def admin_user
       redirect_to( projects_url ) unless current_user.admin?
    end
    
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def image_for(project)
    image = project.icon.presence  || "test.png"
    image_tag( image , alt: project.name, size: "32"  )
  end

  
  def indicate(state)
       if state
          return "green-tick.png"
       else
          return "red-cross.png"
       end 
  end
  
  def status(project)
       if project.active
	return "Active"
       else
        return "Deactivated"
       end 
  end

  def name(project)
       if project.active
          return project.name
       else
          return "Deactivated"
       end 
  end
  
  def edit_mode
      logger.debug self.action_name

      if self.action_name == "show"
           return false
      end

      return true
  end

end

app/views/projects/_collaborations.html.erb
<style type="text/css">  
     select { 
         width:300px; 
            } 
     .span  {
         display: table-cell;
         vertical-align: middle;
            }
.knob {
  display: table;
  height: 100%;
  width: 100%;
  text-align: center;
}
</style>

<div class="row" >
	<div class="col-xs-5 col-sm-5" style="height:35px" >
        <h2> Available </h2>
	</div>
	<div class="col-xs-2 col-sm-2" style="height:35px">
	</div>
	<div class="col-xs-5 col-sm-5" style="height:35px">
        <h2> Selected </h2>
	</div>
</div>
<div class="row">
	<div class="col-xs-5 col-sm-5" >
		<%= form_for( @project ) do |a| %>
		     <%= a.select(:available  , 
		                   options_from_collection_for_select(User.all - @project.users , :id, :name , {} ),
		                   { :prompt => nil },
		                   { :multiple => true, :size => 20 , :id => "available" }) %>
	</div>
	
	<div class="col-xs-2 col-sm-2" style="height:350px" >
             <div class="knob" >
                <% if edit_mode %>
                      <span class="span"> 
                                 <%= a.submit "<<", name: 'move' , value: '<<',   class: "btn btn-primary" %>
                      </span>
                      <span class="span"> 
                                 <%= a.submit ">>", name: 'move' , value: '>>',  class: "btn btn-primary" %>
                      </span>
		<% end %>
             </div>
        </div>

	<div class="col-xs-5 col-sm-5"  >
		     <%= a.select(:selected  , 
		                   options_from_collection_for_select(@project.users, :id, :name  , {} ),
		                   { :prompt =>  nil },
		                   { :multiple => true, :size => 20 , :id => "selected"  } ) %>
		<% end %>
	</div>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :project_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_manage.html.erb
<div class="center container">
  <div class="row">
    <div class="center col-xs-12 col-sm-12" style="height: 30px" >
        <h2> <%= @project.name %>  </h2>
    </div>                             
  </div>
  <div class="row">
    <div class="center col-xs-12 col-sm-12" >
        <h3> <%= status(@project) %>  </h3>
    </div>
  </div>
  <%= render 'projects/collaborations' %>
</div>


<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/_project.html.erb
<li>
  <%= link_to project.name, project %>
  <% if current_user.admin?  %>
    | <%= link_to "delete", project, method: :delete, data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/projects/edit.html.erb
<% provide(:title, 'Projects') %>
<h1>Editing Project</h1>

 <%= render 'projects/manage' %>

app/views/projects/index.html.erb
<% provide(:title, 'Projects') %>
<h1>Projects</h1>

 
 <%= will_paginate %>

<div class="container">
    <div class="container">
        <div class="row">
			<div class="h4 col-xs-2 col-sm-2">Name</div>
			<div class="h4 col-xs-1 col-sm-1">Active</div>
			<div class="h4 col-xs-2 col-sm-2">Actions</div>
			<div class="h4 col-xs-7 col-sm-7"></div>
		</div>
    </div>

	<ul></ul>

	<div class="container">
    <% @projects.each do |project| %>
        <div class="row">
			<div class="col-xs-2 col-sm-2"><%= project.name  %></div>
			<div class="col-xs-2 col-sm-1"><%= image_tag( indicate( project.active ) , title: "Pass/Fail"    , size: 18 )  %></div>
			<div class="col-xs-2 col-sm-2"><%= link_to image_tag("view.svg" , title: "Project Details" , size: 18 ), project_path(project) %>
                                                       <% if current_user.admin  %>
  	    	                                       <%= link_to image_tag("edit.svg" , title: "Edit Project"    , size: 18 ), edit_project_path(project) %>
                                                       <% end %> </div>
			<div class="col-xs-7 col-sm-7"></div>
		</div>
    <% end %>
    </div>
	<div>
	   <% if current_user.admin  %>
	   <%= link_to "New Project", new_project_path , { :class=>"btn" }  %>
	   <% end %>
	</div> 
</div> 
<%= will_paginate %>
 
 

app/views/projects/new.html.erb
<% provide(:title, 'Projects') %>
<h1>Creating Project</h1>

 <%= render 'projects/manage' %>

app/views/projects/show.html.erb
<% provide(:title, 'Projects') %>
<h1><%=  name( @project )  %></h1>


</div>