config/routes.rb
Rails.application.routes.draw do


  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    'settings/index'
  get    'new_connection',      to: 'settings#new'
  get    'collaborations',      to: 'collaborations#index'
  get    'collaborations/:id' , to: 'collaborations#show', as: 'collaboration'
      
  resources :users do
    member do
    end
  end

#  resources :account_activations, only: [:edit]
   resources :password_resets,     only: [:new, :create, :edit, :update]
   resources :projects,            only: [:new, :create, :edit, :update , :index , :show]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/stevenfawcett/oshaka"><%= full_title %></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to full_title(yield(:title)) , root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_main.html.erb
<%= yield() %>

app/views/layouts/_navigator.html.erb
<% if logged_in? %>
  <div id="sidebar">
    <ul>
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to "Users",    users_path %></li>
      <% if current_user.admin? %>
           <li><%= link_to "Settings", settings_index_path %></li>
      <% end %>
     </ul>
   </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'  %>
  </head>

  <body>
  <div class="media-body">
    <%= render 'layouts/header' %>
    <%= render 'layouts/shim' %>
    <div class="container">
      <%= render 'layouts/navigator' %>
      <div class="main-content">
	    <% if logged_in? %>
                <div class="swipe-area"></div>
                <a href="#" data-toggle=".container" id="sidebar-toggle">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </a>
	    <% end %>
            <div class="content">
               <%= render 'layouts/main' %>
               <%= render 'layouts/footer' %>
            </div>
        </div>
    </div>
  </div>
  </body>
<!-- <%= debug(params) if Rails.env.development? %> -->
</html>